language: node_js
node_js:
  - node

script:
  - npm run build

deploy:
  provider: pages:git
  edge: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: dist
  commit_message: Deploy $TRAVIS_TAG
  on:
    tags: true